// Expanded sample ideas with more categories!
const ideas = [
  { id: 1, text: "Plan a surprise candlelit dinner at home", category: "Romantic Dates" },
  { id: 2, text: "Have a pajama movie marathon with hot cocoa", category: "Cozy Nights In" },
  { id: 3, text: "Go hiking at a nearby nature reserve", category: "Outdoor Adventures" },
  { id: 4, text: "Take a weekend road trip to a new city", category: "Travel & Day Trips" },
  { id: 5, text: "Try cooking a three-course meal together", category: "Food & Cooking" },
  { id: 6, text: "Set up a scavenger hunt around your house", category: "Fun Challenges & Games" },
  { id: 7, text: "Leave a handwritten love note in his lunchbox", category: "Surprises & Gifts" },
  { id: 8, text: "Paint a canvas together", category: "Creative & Artsy" },
  { id: 9, text: "Do a couples' meditation session", category: "Self-Care & Relaxation" },
  { id: 10, text: "Make pumpkin spice lattes on a chilly autumn day", category: "Seasonal & Holiday Activities" },
  { id: 11, text: "Binge an entire TV series over a weekend", category: "Movie & TV Marathons" },
  { id: 12, text: "Go rock climbing at an indoor gym", category: "Fitness & Sports" },
  { id: 13, text: "Go thrift shopping for quirky outfits", category: "Shopping & Fashion" },
  { id: 14, text: "Have a private dance party with your favorite songs", category: "Music & Dance" },
  { id: 15, text: "Spend a day at the beach building sandcastles", category: "Beach & Water Fun" },
  { id: 16, text: "Visit a botanical garden in spring", category: "Nature & Parks" },
  { id: 17, text: "Go to a local street festival", category: "Festivals & Events" },
  { id: 18, text: "Take a pottery or painting class", category: "Learning & Hobbies" },
  { id: 19, text: "Build a birdhouse together", category: "DIY & Crafts" },
  { id: 20, text: "Volunteer at an animal shelter", category: "Pets & Animals" },
  { id: 21, text: "Drive along a scenic coastal highway", category: "Road Trips & Drives" },
  { id: 22, text: "Stargaze and wish on shooting stars", category: "Stargazing & Astronomy" },
  { id: 23, text: "Redecorate a room together", category: "Home Improvement & Decorating" },
  { id: 24, text: "Have an at-home spa day with face masks", category: "Spa & Beauty Activities" },
  { id: 25, text: "Try indoor skydiving", category: "Adventure & Extreme Sports" },
  { id: 26, text: "Do a couples photoshoot in a pretty location", category: "Photography & Videography" },
  { id: 27, text: "Grow a herb garden on your windowsill", category: "Gardening & Plants" },
  { id: 28, text: "Play a marathon of board games", category: "Board & Card Games" },
  { id: 29, text: "Visit a museum or go to a play", category: "Cultural Activities (Museums, Theater)" },
  { id: 30, text: "Volunteer for a community clean-up", category: "Volunteer & Charity Activities" },
  { id: 31, text: "Do a guided relaxation or meditation session", category: "Relaxation & Meditation" },
  { id: 32, text: "Go wine tasting at a local vineyard", category: "Wine & Coffee Experiences" },
  { id: 33, text: "Go sledding after the first snow", category: "Seasonal Outdoor Fun (Snow, Leaves, Flowers)" },
  { id: 34, text: "Compete in a video game tournament together", category: "Tech & Gaming Challenges" },
  { id: 35, text: "Make a scrapbook of your favorite memories", category: "Memory & Scrapbook Projects" },
  { id: 36, text: "Host a themed costume party for friends", category: "Parties & Social Gatherings" },
  { id: 37, text: "Take a sunrise hike for breathtaking views", category: "Scenic Exploration & Hikes" },
  { id: 38, text: "Sign up for a new class or workshop together", category: "Learning New Skills Together" },
  { id: 39, text: "Create a couples bucket list", category: "Bucket List Adventures" },
  { id: 40, text: "Visit a state fair and ride the Ferris wheel", category: "Festivals & Fairs" },
  { id: 41, text: "Go to a water park and race down slides", category: "Water Parks & Amusement Parks" },
  { id: 42, text: "Test drive luxury cars or motorcycles", category: "Car & Motorcycle Experiences" },
  { id: 43, text: "Go camping or try glamping together", category: "Camping & Glamping" },
  { id: 44, text: "Take a hot air balloon ride", category: "Hot Air Balloon & Sky Adventures" },
  { id: 45, text: "Escape from a local escape room challenge", category: "Puzzle & Escape Room Challenges" },
  { id: 46, text: "Go ice skating at a festive rink", category: "Ice Skating & Winter Sports" },
  { id: 47, text: "Sing duets at karaoke night", category: "Karaoke & Music Games" },
  { id: 48, text: "Find hidden gems on a local city tour", category: "Local Tours & Hidden Gems" },
  { id: 49, text: "Try a progressive dinner at different restaurants", category: "Food Tastings & Culinary Adventures" },
  { id: 50, text: "Have a sunset picnic in the park", category: "Romantic Picnics & Sunsets" }
];

export default ideas;